name: Publish to GitHub Pages
on:
  workflow_dispatch:

jobs:
  publish-github-pages:
    permissions:
      pages: write
      id-token: write
    uses: ./.github/workflows/publish-github-pages.yml
    secrets:
      APP_ID: ${{ secrets.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
