name: Add risk label

on:
  pull_request:
    types: [opened, edited]

jobs:
  add-risk-label:
    uses: alextheman231/github-actions/.github/workflows/add-risk-label.yml@d1c2bd1832fa5ae4489ed8f9349676045a683655 # v12.8.0
    permissions:
      pull-requests: write
    with:
      APP_ID: ${{ vars.ALEX_UP_BOT_APP_ID }}
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
