name: Add risk label

on:
  pull_request:
    types: [opened, edited]

jobs:
  add-risk-label:
    uses: alextheman231/github-actions/.github/workflows/add-risk-label.yml@a8e567aa7146169f3d858752ffb0f2dfd9ecb70f # v14.0.1
    permissions:
      pull-requests: write
    with:
      CLIENT_ID: ${{ vars.ALEX_UP_BOT_CLIENT_ID }}
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
