name: Add risk label

on:
  pull_request:
    types: [opened, edited]

jobs:
  add-risk-label:
    uses: alextheman231/github-actions/.github/workflows/add-risk-label.yml@3cd2608174c02a8a3f23f8fb490f60446cd88aca # v12.10.2
    permissions:
      pull-requests: write
    with:
      APP_ID: ${{ vars.ALEX_UP_BOT_APP_ID }}
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
