name: Audit dependencies

on:
  pull_request:
    branches: ["main"]

jobs:
  audit-javascript-dependencies:
    permissions:
      contents: read
      pull-requests: write
    uses: alextheman231/github-actions/.github/workflows/audit-javascript-dependencies.yml@0776a9d83e56a216f52b56cb87ec0ff8f84a9368 # v12.3.0
    with:
      pull-request-number: ${{ github.event.pull_request.number }}
      APP_ID: ${{ vars.ALEX_UP_BOT_APP_ID }}
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
