name: Audit dependencies

on:
  pull_request:
    branches: ["main"]
    paths:
      - "**/pnpm-lock.yaml"

jobs:
  audit-javascript-dependencies:
    permissions:
      contents: read
      pull-requests: write
    uses: alextheman231/github-actions/.github/workflows/audit-javascript-dependencies.yml@a8e567aa7146169f3d858752ffb0f2dfd9ecb70f # v14.0.1
    with:
      pull-request-number: ${{ github.event.pull_request.number }}
      node-version: 26
      CLIENT_ID: ${{ vars.ALEX_UP_BOT_CLIENT_ID }}
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
