name: Check labels

on:
  pull_request:
    types: [labeled, unlabeled, synchronize]

jobs:
  check-labels:
    permissions:
      pull-requests: read
    uses: alextheman231/github-actions/.github/workflows/check-labels.yml@a8e567aa7146169f3d858752ffb0f2dfd9ecb70f # v14.0.1
    with:
      pull-request-number: ${{ github.event.pull_request.number }}
      CLIENT_ID: ${{ vars.ALEX_UP_BOT_CLIENT_ID }}
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
