name: Check labels

on:
  pull_request:
    types: [labeled, unlabeled, synchronize]

jobs:
  check-labels:
    permissions:
      pull-requests: read
    uses: alextheman231/github-actions/.github/workflows/check-labels.yml@77ec4714869dc7574206ff9142a156dd8d49b671 # v12.7.5
    with:
      pull-request-number: ${{ github.event.pull_request.number }}
      APP_ID: ${{ vars.ALEX_UP_BOT_APP_ID }}
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
