name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  merge_group:
    types: [checks_requested]

permissions:
  contents: read

jobs:
  package-ci:
    uses: alextheman231/github-actions/.github/workflows/package-ci.yml@3cd2608174c02a8a3f23f8fb490f60446cd88aca # v12.10.2
    with:
      node-version: 26

  actions-ci:
    uses: alextheman231/github-actions/.github/workflows/actions-ci.yml@3cd2608174c02a8a3f23f8fb490f60446cd88aca # v12.10.2

  end-to-end-ci:
    uses: alextheman231/github-actions/.github/workflows/end-to-end-node-package-ci.yml@3cd2608174c02a8a3f23f8fb490f60446cd88aca # v12.10.2
    with:
      node-version: 26
