name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  merge_group:
    types: [checks_requested]

permissions:
  contents: read

jobs:
  package-ci:
    uses: alextheman231/github-actions/.github/workflows/package-ci.yml@bba094b0c09dda59228db6437a5231ba0538d09a # v12.7.0
    with:
      node-version: 26

  actions-ci:
    uses: alextheman231/github-actions/.github/workflows/actions-ci.yml@bba094b0c09dda59228db6437a5231ba0538d09a # v12.7.0

  end-to-end-ci:
    uses: alextheman231/github-actions/.github/workflows/end-to-end-node-package-ci.yml@bba094b0c09dda59228db6437a5231ba0538d09a # v12.7.0
    with:
      node-version: 26
