name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  merge_group:
    types: [checks_requested]

permissions:
  contents: read

jobs:
  package-ci:
    uses: alextheman231/github-actions/.github/workflows/package-ci.yml@760f1347c1597e458ce3e966112d7278ed15c059 # v12.5.1
    with:
      node-version: 26

  actions-ci:
    uses: alextheman231/github-actions/.github/workflows/actions-ci.yml@760f1347c1597e458ce3e966112d7278ed15c059 # v12.5.1

  end-to-end-ci:
    uses: alextheman231/github-actions/.github/workflows/end-to-end-node-package-ci.yml@760f1347c1597e458ce3e966112d7278ed15c059 # v12.5.1
    with:
      node-version: 26
