name: Commit a version change
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  check-major-version:
    permissions:
      contents: write
      pull-requests: write
    uses: alextheman231/github-actions/.github/workflows/commit-version-change.yml@f1ff1cf13a2143e1e04a55da4b1fd77c2adb9b78 # v14.0.0
    with:
      CLIENT_ID: ${{ vars.ALEX_UP_BOT_CLIENT_ID }}
      version-type: major
      node-version: 26
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY}}

  check-minor-version:
    permissions:
      contents: write
      pull-requests: write
    uses: alextheman231/github-actions/.github/workflows/commit-version-change.yml@f1ff1cf13a2143e1e04a55da4b1fd77c2adb9b78 # v14.0.0
    with:
      CLIENT_ID: ${{ vars.ALEX_UP_BOT_CLIENT_ID }}
      version-type: minor
      node-version: 26
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY}}

  check-patch-version:
    permissions:
      contents: write
      pull-requests: write
    uses: alextheman231/github-actions/.github/workflows/commit-version-change.yml@f1ff1cf13a2143e1e04a55da4b1fd77c2adb9b78 # v14.0.0
    with:
      CLIENT_ID: ${{ vars.ALEX_UP_BOT_CLIENT_ID }}
      version-type: patch
      node-version: 26
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY}}
