name: Comment outdated dependencies

on:
  pull_request:
    branches: ["main"]

jobs:
  comment-outdated:
    uses: alextheman231/github-actions/.github/workflows/comment-outdated.yml@84fe032bc2c67a442beaae6648323087929d34c0 # v11.0.7
    if: ${{ github.head_ref == 'alex-up-bot/update-dependencies' }}
    permissions:
      actions: read
      checks: write
      contents: read
      pull-requests: write
    with:
      pull-request-number: ${{ github.event.pull_request.number }}
    secrets:
      APP_ID: ${{ secrets.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
