name: Commit a version change
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  check-major-version:
    permissions:
      contents: write
      pull-requests: write
    uses: alextheman231/github-actions/.github/workflows/commit-version-change.yml@3a7c224f60dbd26c8e2f31738236b6cbc8dd96e7 # v12.0.0
    with:
      version-type: major
    secrets:
      APP_ID: ${{ vars.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY}}

  check-minor-version:
    permissions:
      contents: write
      pull-requests: write
    uses: alextheman231/github-actions/.github/workflows/commit-version-change.yml@3a7c224f60dbd26c8e2f31738236b6cbc8dd96e7 # v12.0.0
    with:
      version-type: minor
    secrets:
      APP_ID: ${{ vars.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY}}

  check-patch-version:
    permissions:
      contents: write
      pull-requests: write
    uses: alextheman231/github-actions/.github/workflows/commit-version-change.yml@3a7c224f60dbd26c8e2f31738236b6cbc8dd96e7 # v12.0.0
    with:
      version-type: patch
    secrets:
      APP_ID: ${{ vars.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY}}
