name: Commit a version change
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  check-major-version:
    permissions:
      contents: write
      pull-requests: write
    uses: alextheman231/github-actions/.github/workflows/commit-version-change.yml@a8e567aa7146169f3d858752ffb0f2dfd9ecb70f # v14.0.1
    with:
      CLIENT_ID: ${{ vars.ALEX_UP_BOT_CLIENT_ID }}
      version-type: major
      node-version: 26
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY}}

  check-minor-version:
    permissions:
      contents: write
      pull-requests: write
    uses: alextheman231/github-actions/.github/workflows/commit-version-change.yml@a8e567aa7146169f3d858752ffb0f2dfd9ecb70f # v14.0.1
    with:
      CLIENT_ID: ${{ vars.ALEX_UP_BOT_CLIENT_ID }}
      version-type: minor
      node-version: 26
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY}}

  check-patch-version:
    permissions:
      contents: write
      pull-requests: write
    uses: alextheman231/github-actions/.github/workflows/commit-version-change.yml@a8e567aa7146169f3d858752ffb0f2dfd9ecb70f # v14.0.1
    with:
      CLIENT_ID: ${{ vars.ALEX_UP_BOT_CLIENT_ID }}
      version-type: patch
      node-version: 26
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY}}
