name: Create feature docs

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-feature-docs:
    uses: alextheman231/github-actions/.github/workflows/create-feature-docs.yml@06984a14da9331ddb4f308379582012bce780b0c # v10.0.0
    secrets:
      APP_ID: ${{ secrets.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
