name: Create pull request templates

on:
  workflow_dispatch:
  schedule:
    - cron: 0 21 * * 0

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request-templates:
    if: ${{ github.repository == 'alextheman231/utility' }}
    uses: alextheman231/github-actions/.github/workflows/create-pull-request-templates.yml@84fe032bc2c67a442beaae6648323087929d34c0 # v11.0.7
    secrets:
      APP_ID: ${{ secrets.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
