name: Create GitHub Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-github-release:
    if: ${{ github.repository == 'alextheman231/utility' }}
    uses: alextheman231/github-actions/.github/workflows/create-github-release.yml@5a51ff516a9036a0f71712e2028f28d7e6fe955b # v12.0.1
    secrets:
      APP_ID: ${{ vars.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
