name: Publish to GitHub Pages
on:
  workflow_dispatch:

jobs:
  publish-github-pages:
    permissions:
      pages: write
      id-token: write
    uses: alextheman231/github-actions/.github/workflows/publish-github-pages.yml@77bb6d670a2c8c1d90b6571c93787f37dafb2e19 # v13.0.1
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
    with:
      CLIENT_ID: ${{ vars.ALEX_UP_BOT_CLIENT_ID }}
      path: docs/features/html
      build-configs: true
      node-version: 26
