name: Publish the package

on:
  push:
    branches:
      - main

jobs:
  npm-registry-publish:
    permissions:
      id-token: write
    if: ${{ github.repository == 'alextheman231/utility' }}
    uses: alextheman231/github-actions/.github/workflows/npm-registry-publish.yml@77bb6d670a2c8c1d90b6571c93787f37dafb2e19 # v13.0.1
    with:
      node-version: 26

  create-github-release:
    needs: npm-registry-publish
    permissions:
      contents: write
    if: needs.npm-registry-publish.outputs.did_publish == 'true'
    uses: alextheman231/github-actions/.github/workflows/create-github-release.yml@77bb6d670a2c8c1d90b6571c93787f37dafb2e19 # v13.0.1
    with:
      node-version: 26
      CLIENT_ID: ${{ vars.ALEX_UP_BOT_CLIENT_ID }}
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}

  publish-github-pages:
    permissions:
      pages: write
      id-token: write
    needs: create-github-release
    if: needs.create-github-release.outputs.did_release == 'true'
    uses: alextheman231/github-actions/.github/workflows/publish-github-pages.yml@77bb6d670a2c8c1d90b6571c93787f37dafb2e19 # v13.0.1
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
    with:
      CLIENT_ID: ${{ vars.ALEX_UP_BOT_CLIENT_ID }}
      path: docs/features/html
      build-configs: true
      node-version: 26
