name: Publish to GitHub Pages
on:
  workflow_dispatch:

jobs:
  publish-github-pages:
    permissions:
      pages: write
      id-token: write
    uses: alextheman231/github-actions/.github/workflows/publish-github-pages.yml@77ec4714869dc7574206ff9142a156dd8d49b671 # v12.7.5
    secrets:
      APP_ID: ${{ vars.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
    with:
      path: docs/features/html
      build-configs: true
      node-version: 26
