name: Publish to GitHub Pages
on:
  workflow_dispatch:

jobs:
  publish-github-pages:
    permissions:
      pages: write
      id-token: write
    uses: alextheman231/github-actions/.github/workflows/publish-github-pages.yml@690ddbb17a4591efc36cd68216623b77977ebdc8 # v11.1.0
    secrets:
      APP_ID: ${{ secrets.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
    with:
      path: docs/features/html
      build-configs: true
