name: Publish the package

on:
  push:
    branches:
      - main

jobs:
  check-npm-version:
    permissions:
      contents: read
    uses: alextheman231/github-actions/.github/workflows/report-npm-version-existence.yml@2e6f55a35af0696b45f5fd2facf87164d4e64533 # v14.0.2
    with:
      node-version: 26

  check-version-tag:
    permissions:
      contents: read
    uses: alextheman231/github-actions/.github/workflows/report-version-tag-existence.yml@2e6f55a35af0696b45f5fd2facf87164d4e64533 # v14.0.2
    with:
      CLIENT_ID: ${{ vars.ALEX_UP_BOT_CLIENT_ID }}
      node-version: 26
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}

  check-release-note:
    permissions:
      contents: read
    uses: alextheman231/github-actions/.github/workflows/report-release-note-existence.yml@2e6f55a35af0696b45f5fd2facf87164d4e64533 # v14.0.2
    with:
      CLIENT_ID: ${{ vars.ALEX_UP_BOT_CLIENT_ID }}
      node-version: 26
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}

  npm-registry-publish:
    needs: [check-npm-version, check-version-tag, check-release-note]
    if: ${{ needs.check-npm-version.outputs.version-exists == 'false' && needs.check-version-tag.outputs.tag-exists == 'false' && needs.check-release-note.outputs.release-note-found == 'true' }}
    permissions:
      id-token: write
    uses: alextheman231/github-actions/.github/workflows/npm-registry-publish.yml@2e6f55a35af0696b45f5fd2facf87164d4e64533 # v14.0.2
    with:
      node-version: 26

  create-github-release:
    needs: [check-version-tag, check-release-note]
    permissions:
      contents: write
    if: ${{ needs.check-version-tag.outputs.tag-exists == 'false' && needs.check-release-note.outputs.release-note-found == 'true' }}
    uses: alextheman231/github-actions/.github/workflows/create-github-release.yml@2e6f55a35af0696b45f5fd2facf87164d4e64533 # v14.0.2
    with:
      node-version: 26
      CLIENT_ID: ${{ vars.ALEX_UP_BOT_CLIENT_ID }}
      tag: ${{ needs.check-version-tag.outputs.tag }}
      release-note-path: ${{ needs.check-release-note.outputs.release-note-path }}
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}

  publish-github-pages:
    permissions:
      pages: write
      id-token: write
    needs: [create-github-release]
    uses: alextheman231/github-actions/.github/workflows/publish-github-pages.yml@2e6f55a35af0696b45f5fd2facf87164d4e64533 # v14.0.2
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
    with:
      CLIENT_ID: ${{ vars.ALEX_UP_BOT_CLIENT_ID }}
      path: docs/features/html
      build-configs: true
      node-version: 26
