name: Restrict alex-up-bot branches

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  restrict-alex-up-bot-branches:
    uses: alextheman231/github-actions/.github/workflows/restrict-alex-up-bot-branches.yml@2e6f55a35af0696b45f5fd2facf87164d4e64533 # v14.0.2
    with:
      CLIENT_ID: ${{ vars.ALEX_UP_BOT_CLIENT_ID }}
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
