name: Restrict alex-up-bot branches

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  restrict-alex-up-bot-branches:
    uses: alextheman231/github-actions/.github/workflows/restrict-alex-up-bot-branches.yml@e4a092a202ca5bac12242bbf53a046f32a08455a # v10.4.0
    secrets:
      APP_ID: ${{ secrets.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
