name: Scheduled Patch Release

on:
  workflow_dispatch:
  schedule:
    - cron: 0 21 1 * *

jobs:
  scheduled-patch-release:
    permissions:
      contents: write
    if: ${{ github.repository == 'alextheman231/utility' }}
    uses: alextheman231/github-actions/.github/workflows/scheduled-patch-release.yml@aa8a3ef9f3e8d4e820402e4f6bf811af5298c3a9 # v12.4.1
    with:
      node-version: 26
    secrets:
      APP_ID: ${{ vars.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
