name: Scheduled Patch Release

on:
  workflow_dispatch:
  schedule:
    - cron: 0 21 1 * *

jobs:
  scheduled-patch-release:
    permissions:
      contents: write
    if: ${{ github.repository == 'alextheman231/utility' }}
    uses: alextheman231/github-actions/.github/workflows/scheduled-patch-release.yml@77bb6d670a2c8c1d90b6571c93787f37dafb2e19 # v13.0.1
    with:
      CLIENT_ID: ${{ vars.ALEX_UP_BOT_CLIENT_ID }}
      node-version: 26
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
