name: Scheduled Patch Release

on:
  workflow_dispatch:
  schedule:
    - cron: 0 21 1 * *

jobs:
  scheduled-patch-release:
    permissions:
      contents: write
    if: ${{ github.repository == 'alextheman231/utility' }}
    uses: alextheman231/github-actions/.github/workflows/scheduled-patch-release.yml@2e6f55a35af0696b45f5fd2facf87164d4e64533 # v14.0.2
    with:
      CLIENT_ID: ${{ vars.ALEX_UP_BOT_CLIENT_ID }}
      node-version: 26
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
