name: Update Dependencies
on:
  workflow_dispatch:
  schedule:
    - cron: 0 21 * * 5

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    if: ${{ github.repository == 'alextheman231/utility' }}
    uses: alextheman231/github-actions/.github/workflows/update-dependencies.yml@ec0a721b5d0c0f9fd8b86437636f9bcbc64218ef # v11.0.1
    secrets:
      APP_ID: ${{ secrets.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
    with:
      update_pnpm: true
      update_javascript_dependencies: true
      update_actions: true
