name: Update Dependencies
on:
  workflow_dispatch:
  schedule:
    - cron: 0 21 * * 5

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    if: ${{ github.repository == 'alextheman231/utility' }}
    uses: alextheman231/github-actions/.github/workflows/update-dependencies.yml@6d446b591dd8f09c45f434211e1e5d6773bea4f6 # v13.0.2
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
    with:
      CLIENT_ID: ${{ vars.ALEX_UP_BOT_CLIENT_ID }}
      update_pnpm: true
      update_javascript_dependencies: true
      update_actions: true
      node-version: 26
